services:
  reform:
    build: .
    user: root
    command: /lib/systemd/systemd
    stdin_open: true
    tty: true
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - ./reform:/home/reform/reform
      - ./reform_discovery:/home/reform/reform_discovery
      - ./reform.conf:/etc/nginx/sites-enabled/reform.conf
    deploy:
      resources:
        limits:
          pids: 10000